<a href="https://colab.research.google.com/github/CasCard/Machile-Learning-Project/blob/master/tf.data_Guide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
tf.random.set_seed(1)
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

print(tf.__version__)

TensorFlow 2.x selected.
2.0.0


In [0]:
import pathlib
np.set_printoptions(precision=4)


In [3]:
data=tf.data.Dataset.from_tensor_slices([8,3,0,8,2,1])
data

<TensorSliceDataset shapes: (), types: tf.int32>

In [4]:
for elem in data:
  print(elem.numpy())

8
3
0
8
2
1


In [5]:
it=iter(data)
print(next(it).numpy())

8


In [6]:
print(data.reduce(0,lambda state,value:state+value).numpy())

22


In [7]:
dataset1=tf.data.Dataset.from_tensor_slices(tf.random.uniform([4,10]))
for element in dataset1:
  print(element.numpy())

[0.1651 0.9015 0.631  0.4345 0.2919 0.6425 0.9758 0.4351 0.6601 0.6049]
[0.6366 0.6144 0.8893 0.6278 0.532  0.026  0.4409 0.2527 0.8862 0.8873]
[0.7873 0.0596 0.0711 0.3084 0.2512 0.9085 0.4715 0.2424 0.633  0.586 ]
[0.91   0.5701 0.4964 0.5939 0.5414 0.4429 0.2925 0.7339 0.9197 0.6685]


In [8]:
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [0]:
dataset2=tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([4]),
     tf.random.uniform([4,100],maxval=100,dtype=tf.int32))
)

In [10]:
dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [11]:
dataset3=tf.data.Dataset.zip((dataset1,dataset2))
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(100,), dtype=tf.int32, name=None)))

In [12]:
for elem in dataset3:
  print(elem)

(<tf.Tensor: id=63, shape=(10,), dtype=float32, numpy=
array([0.1651, 0.9015, 0.631 , 0.4345, 0.2919, 0.6425, 0.9758, 0.4351,
       0.6601, 0.6049], dtype=float32)>, (<tf.Tensor: id=64, shape=(), dtype=float32, numpy=0.51010704>, <tf.Tensor: id=65, shape=(100,), dtype=int32, numpy=
array([15, 18, 76, 96, 14, 19, 14, 34, 63, 59, 36, 90, 54,  7, 43, 64, 44,
       95, 35, 24, 43, 76, 38, 31, 95, 11, 71, 24, 38, 19, 14, 17, 66, 81,
       24, 45,  6, 70,  7, 34, 61,  3, 45, 96, 27, 43, 32, 71, 40, 16, 69,
       76, 64, 58, 69, 13, 69, 92, 40, 69,  0, 80, 63, 85,  5, 51,  7, 38,
       23, 61, 66, 88, 26,  5, 17, 82, 59,  0, 80, 45, 73, 95, 75, 90, 35,
       19, 76, 41, 47, 30, 17, 24, 88, 38, 81, 49, 64, 46, 95, 65],
      dtype=int32)>))
(<tf.Tensor: id=66, shape=(10,), dtype=float32, numpy=
array([0.6366, 0.6144, 0.8893, 0.6278, 0.532 , 0.026 , 0.4409, 0.2527,
       0.8862, 0.8873], dtype=float32)>, (<tf.Tensor: id=67, shape=(), dtype=float32, numpy=0.44353175>, <tf.Tensor: id=68, s

In [13]:
dataset4=tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0,0],[1,2]],values=[1,2],dense_shape=[3,4]))
dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [14]:
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor

In [15]:
dataset1=tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4,10],minval=1,maxval=10,dtype=tf.int32))
dataset1

<TensorSliceDataset shapes: (10,), types: tf.int32>

In [16]:
for elem in dataset1:
  print(elem.numpy())

[2 4 4 4 5 7 2 9 9 6]
[5 7 2 4 5 3 1 3 2 3]
[6 4 2 2 6 1 7 3 8 4]
[9 2 6 8 6 4 9 3 2 2]


In [17]:
dataset2=tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([4]),
     tf.random.uniform([4,100],maxval=100,dtype=tf.int32))
)
dataset2

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>

In [18]:
for test in dataset2:
  print(test)

(<tf.Tensor: id=111, shape=(), dtype=float32, numpy=0.734782>, <tf.Tensor: id=112, shape=(100,), dtype=int32, numpy=
array([55, 10, 15, 35, 52, 88, 93,  9, 63, 26,  1, 59,  7, 93, 44, 36, 76,
       50, 98, 51, 18, 38, 50, 31, 56, 37, 21, 79, 45,  4, 42, 33, 79,  0,
       82, 45, 16, 50, 24, 38, 50, 75, 92, 99, 53, 16, 56, 50, 58, 43, 68,
       65, 24, 45, 14, 84, 40, 50, 68, 98, 84, 27, 43, 35, 64, 35, 48, 97,
        0, 46, 12, 16, 19, 81, 77, 64, 52, 87, 43, 44, 70, 72, 51, 65, 25,
       56, 87, 18, 70, 32, 27, 77, 40, 91, 55, 10, 30, 19, 63, 85],
      dtype=int32)>)
(<tf.Tensor: id=113, shape=(), dtype=float32, numpy=0.14221263>, <tf.Tensor: id=114, shape=(100,), dtype=int32, numpy=
array([23, 27, 53, 54, 42, 29, 24, 71, 64, 93, 30, 71,  7, 63, 26, 17, 30,
       58, 60,  4, 57, 87, 88, 13, 26, 73, 35, 67, 70, 42, 51, 94, 19, 33,
       44, 51,  8, 60, 51, 74, 52, 10, 10, 45, 86, 55, 64, 89,  6, 19,  3,
       59, 27, 73, 22, 69, 28,  8, 65, 45, 38, 73, 83, 45, 27, 53, 83, 97,


In [19]:
dataset3=tf.data.Dataset.zip((dataset1,dataset2))
dataset3

<ZipDataset shapes: ((10,), ((), (100,))), types: (tf.int32, (tf.float32, tf.int32))>

In [20]:
for a,(b,c) in dataset3:
  print('shapes: {a.shape},{b.shape},{c.shape}'.format(a=a,b=b,c=c))

shapes: (10,),(),(100,)
shapes: (10,),(),(100,)
shapes: (10,),(),(100,)
shapes: (10,),(),(100,)


In [21]:
train,test=tf.keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [22]:
images,labels=train
images=images/255
dataset=tf.data.Dataset.from_tensor_slices((images,labels))
dataset

<TensorSliceDataset shapes: ((28, 28), ()), types: (tf.float64, tf.uint8)>

In [23]:
def count(stop):
  i=0
  while i<stop:
    yield i
    i+=1

for n in count(5):
  print(n)

0
1
2
3
4


In [0]:
ds_counter=tf.data.Dataset.from_generator(count,args=[25],output_types=tf.int32,output_shapes=(),)


In [25]:
for count_batch in ds_counter.repeat().batch(10).take(5):
  print(count_batch.numpy())

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24  0  1  2  3  4]
[ 5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24]


In [0]:
def gen_series():
  i=0
  while True:
    size=np.random.randint(0,10)
    yield i,np.random.normal(size=(size,))
    i += 1

In [27]:
for i ,series in gen_series():
  print(i,":",str(series))
  if i>5:
    break

0 : []
1 : [ 1.062  -1.8065 -0.8627 -1.0398  1.2834]
2 : [-0.25    0.7631  0.2066  0.7082 -0.8243]
3 : [ 0.3825  0.7126  0.5994  0.2921 -0.0825 -0.3167 -0.3643  0.8588 -1.0195]
4 : [-1.975   0.4152 -0.8867  0.7917  2.2379]
5 : [-1.425   1.8065  0.0465 -1.2616]
6 : [0.2547]


In [28]:
ds_series=tf.data.Dataset.from_generator(
    gen_series,
    output_types=(tf.int32,tf.float32),
    output_shapes=((),(None,)))

ds_series

<DatasetV1Adapter shapes: ((), (None,)), types: (tf.int32, tf.float32)>

In [29]:
ds_series_batch=ds_series.shuffle(20).padded_batch(10,padded_shapes=([],[None]))

ids,sequence_batch=next(iter(ds_series_batch))
print(ids.numpy())
print()
print(sequence_batch.numpy())

[13  9 10 22  4  8 25 20 18 14]

[[-0.9652 -0.497   0.2082  2.1972 -0.6454 -0.4111 -1.0523  0.2665 -0.1245]
 [ 1.6224  0.9955 -0.2854  0.      0.      0.      0.      0.      0.    ]
 [ 2.5722  0.2153 -0.0837 -0.2062  0.501   0.      0.      0.      0.    ]
 [-0.6401  0.6029  0.2827 -0.0254  0.1197 -0.9855  0.1702  0.      0.    ]
 [ 1.5059  0.      0.      0.      0.      0.      0.      0.      0.    ]
 [-0.3977 -0.2637  1.7265 -0.2485 -0.4357 -0.1011  0.9689  0.      0.    ]
 [-1.4182  0.0426  0.      0.      0.      0.      0.      0.      0.    ]
 [-1.0617 -1.2125  0.3531  1.3339  0.      0.      0.      0.      0.    ]
 [ 0.4489  0.1679 -0.6302 -1.8899 -0.7641  0.      0.      0.      0.    ]
 [-0.1045  1.0963 -2.8001 -0.4756 -0.6309  0.1267  0.8929  0.      0.    ]]


In [30]:
flowers=tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True
)

228818944/228813984 [==============================] - 2s 0us/step


In [31]:
img_gen=tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255,rotation_range=20)
images,label=next(img_gen.flow_from_directory(flowers))

Found 3670 images belonging to 5 classes.


In [32]:
print(images.dtype,images.shape)
print(label.dtype,label.shape)

float32 (32, 256, 256, 3)
float32 (32, 5)


In [33]:
ds=tf.data.Dataset.from_generator(
    img_gen.flow_from_directory,args=[flowers],
    output_types=(tf.float32,tf.float32),
    output_shapes=([32,256,256,3],[32,5])
)
ds

<DatasetV1Adapter shapes: ((32, 256, 256, 3), (32, 5)), types: (tf.float32, tf.float32)>

In [34]:
# Consuming TFRecord data
fsns_test_file = tf.keras.utils.get_file("fsns.tfrec", "https://storage.googleapis.com/download.tensorflow.org/data/fsns-20160927/testdata/fsns-00000-of-00001")

7905280/7904079 [==============================] - 0s 0us/step


In [35]:
dataset=tf.data.TFRecordDataset(filenames=[fsns_test_file])
dataset

<TFRecordDatasetV2 shapes: (), types: tf.string>

In [36]:
raw_example=next(iter(dataset))
parsed=tf.train.Example.FromString(raw_example.numpy())
parsed.features.feature['image/text']

bytes_list {
  value: "Rue Perreyon"
}

In [37]:
directory_url = 'https://storage.googleapis.com/download.tensorflow.org/data/illiad/'
file_names = ['cowper.txt', 'derby.txt', 'butler.txt']

file_paths = [
    tf.keras.utils.get_file(file_name, directory_url + file_name)
    for file_name in file_names
]

811008/807992 [==============================] - 0s 0us/step


In [38]:
dataset=tf.data.TextLineDataset(file_paths)
for line in dataset.take(5):
  print(line.numpy())

b"\xef\xbb\xbfAchilles sing, O Goddess! Peleus' son;"
b'His wrath pernicious, who ten thousand woes'
b"Caused to Achaia's host, sent many a soul"
b'Illustrious into Ades premature,'
b'And Heroes gave (so stood the will of Jove)'


In [43]:
# Consuming Text Data
files_ds=tf.data.Dataset.from_tensor_slices(file_paths)
lines_ds=files_ds.interleave(tf.data.TextLineDataset,cycle_length=3)

for i,line in enumerate(lines_ds.take(9)):
  if i%3 ==0:
    print()
  print(line.numpy())


b"\xef\xbb\xbfAchilles sing, O Goddess! Peleus' son;"
b"\xef\xbb\xbfOf Peleus' son, Achilles, sing, O Muse,"
b'\xef\xbb\xbfSing, O goddess, the anger of Achilles son of Peleus, that brought'

b'His wrath pernicious, who ten thousand woes'
b'The vengeance, deep and deadly; whence to Greece'
b'countless ills upon the Achaeans. Many a brave soul did it send'

b"Caused to Achaia's host, sent many a soul"
b'Unnumbered ills arose; which many a soul'
b'hurrying down to Hades, and many a hero did it yield a prey to dogs and'


In [44]:
titanic_file=tf.keras.utils.get_file("train.csv", "https://storage.googleapis.com/tf-datasets/titanic/train.csv")
titanic_lines=tf.data.TextLineDataset(titanic_file)

32768/30874 [===============================] - 0s 0us/step


In [45]:
for line in titanic_lines.take(10):
  print(line.numpy())

b'survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone'
b'0,male,22.0,1,0,7.25,Third,unknown,Southampton,n'
b'1,female,38.0,1,0,71.2833,First,C,Cherbourg,n'
b'1,female,26.0,0,0,7.925,Third,unknown,Southampton,y'
b'1,female,35.0,1,0,53.1,First,C,Southampton,n'
b'0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y'
b'0,male,2.0,3,1,21.075,Third,unknown,Southampton,n'
b'1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n'
b'1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n'
b'1,female,4.0,1,1,16.7,Third,G,Southampton,n'


In [46]:
def survived(line):
  return tf.not_equal(tf.strings.substr(line,0,1),"0")

survivors = titanic_lines.skip(1).filter(survived)

for line in survivors.take(10):
  print(line.numpy())

b'1,female,38.0,1,0,71.2833,First,C,Cherbourg,n'
b'1,female,26.0,0,0,7.925,Third,unknown,Southampton,y'
b'1,female,35.0,1,0,53.1,First,C,Southampton,n'
b'1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n'
b'1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n'
b'1,female,4.0,1,1,16.7,Third,G,Southampton,n'
b'1,male,28.0,0,0,13.0,Second,unknown,Southampton,y'
b'1,female,28.0,0,0,7.225,Third,unknown,Cherbourg,y'
b'1,male,28.0,0,0,35.5,First,A,Southampton,y'
b'1,female,38.0,1,5,31.3875,Third,unknown,Southampton,n'


In [47]:
# Consuming CSV data
titanic_file=tf.keras.utils.get_file("train.csv", "https://storage.googleapis.com/tf-datasets/titanic/train.csv")
df=pd.read_csv(titanic_file,index_col=None)
df.head()

survived     sex   age  ...     deck  embark_town  alone
0         0    male  22.0  ...  unknown  Southampton      n
1         1  female  38.0  ...        C    Cherbourg      n
2         1  female  26.0  ...  unknown  Southampton      y
3         1  female  35.0  ...        C  Southampton      n
4         0    male  28.0  ...  unknown   Queenstown      y

[5 rows x 10 columns]

In [48]:
titanic_slices=tf.data.Dataset.from_tensor_slices(dict(df))

for feature_batch in titanic_slices.take(1):
  for key, value in feature_batch.items():
    print("  {!r:20s}: {}".format(key,value))

  'survived'          : 0
  'sex'               : b'male'
  'age'               : 22.0
  'n_siblings_spouses': 1
  'parch'             : 0
  'fare'              : 7.25
  'class'             : b'Third'
  'deck'              : b'unknown'
  'embark_town'       : b'Southampton'
  'alone'             : b'n'


In [49]:
titanic_batches=tf.data.experimental.make_csv_dataset(
    titanic_file,batch_size=4,
    label_name="survived")

Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.
Instructions for updating:
Use `tf.data.Dataset.shuffle(buffer_size, seed)` followed by `tf.data.Dataset.repeat(count)`. Static tf.data optimizations will take care of using the fused implementation.


In [50]:
for feature_batch,label_batch in titanic_batches.take(1):
  print("'survived': {}".format(label_batch))
  print("features:")
  for key, value in feature_batch.items():
    print(" {!r:20s}: {}".format(key,value))

'survived': [1 0 1 1]
features:
 'sex'               : [b'female' b'male' b'female' b'female']
 'age'               : [50. 28. 35. 28.]
 'n_siblings_spouses': [0 2 0 1]
 'parch'             : [1 0 0 0]
 'fare'              : [26.     21.6792 21.     15.5   ]
 'class'             : [b'Second' b'Third' b'Second' b'Third']
 'deck'              : [b'unknown' b'unknown' b'unknown' b'unknown']
 'embark_town'       : [b'Southampton' b'Cherbourg' b'Southampton' b'Queenstown']
 'alone'             : [b'n' b'n' b'y' b'n']


In [0]:
titanic_batches=tf.data.experimental.make_csv_dataset(
    titanic_file,batch_size=4,
    label_name="survived"
    ,select_columns=['class','fare','survived']
)

In [58]:
for feature_batch,label_batch in titanic_batches.take(1):
  print("'survived': {}".format(label_batch))
  for key,value in feature_batch.items():
    print("  {!r:20s}: {}".format(key,value))

'survived': [0 0 0 0]
  'fare'              : [7.65   9.5    7.7333 7.8542]
  'class'             : [b'Third' b'Third' b'Third' b'Third']


In [59]:
titanic_types=[tf.int32,tf.string,tf.float32,tf.int32,tf.int32,tf.float32,tf.string,tf.string,tf.string,tf.string]
dataset=tf.data.experimental.CsvDataset(titanic_file,titanic_types,header=True)

for line in dataset.take(10):
  print([item.numpy() for item in line])

[0, b'male', 22.0, 1, 0, 7.25, b'Third', b'unknown', b'Southampton', b'n']
[1, b'female', 38.0, 1, 0, 71.2833, b'First', b'C', b'Cherbourg', b'n']
[1, b'female', 26.0, 0, 0, 7.925, b'Third', b'unknown', b'Southampton', b'y']
[1, b'female', 35.0, 1, 0, 53.1, b'First', b'C', b'Southampton', b'n']
[0, b'male', 28.0, 0, 0, 8.4583, b'Third', b'unknown', b'Queenstown', b'y']
[0, b'male', 2.0, 3, 1, 21.075, b'Third', b'unknown', b'Southampton', b'n']
[1, b'female', 27.0, 0, 2, 11.1333, b'Third', b'unknown', b'Southampton', b'n']
[1, b'female', 14.0, 1, 0, 30.0708, b'Second', b'unknown', b'Cherbourg', b'n']
[1, b'female', 4.0, 1, 1, 16.7, b'Third', b'G', b'Southampton', b'n']
[0, b'male', 20.0, 0, 0, 8.05, b'Third', b'unknown', b'Southampton', b'y']


In [62]:
%%writefile missing.csv
1,2,3,4
,2,3,4
1,,3,4
1,2,,4
1,2,3,
,,,

Writing missing.csv


In [63]:
record_defaults=[999,999,999,999]
dataset=tf.data.experimental.CsvDataset("missing.csv",record_defaults)
dataset=dataset.map(lambda *items:tf.stack(items))
dataset

<MapDataset shapes: (4,), types: tf.int32>

In [64]:
for line in dataset:
  print(line.numpy())

[1 2 3 4]
[999   2   3   4]
[  1 999   3   4]
[  1   2 999   4]
[  1   2   3 999]
[999 999 999 999]


In [65]:
record_defaults=[999,999]
dataset=tf.data.experimental.CsvDataset("missing.csv",record_defaults,select_cols=[1,3])
dataset=dataset.map(lambda *items:tf.stack(items))
dataset

<MapDataset shapes: (2,), types: tf.int32>

In [66]:
for line in dataset:
  print(line.numpy())

[2 4]
[2 4]
[999   4]
[2 4]
[  2 999]
[999 999]


In [0]:
flowers_root = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)
flowers_root = pathlib.Path(flowers_root)

In [69]:
for item in flowers_root.glob("*"):
  print(item.name)

roses
tulips
dandelion
LICENSE.txt
daisy
sunflowers


In [70]:
list_ds=tf.data.Dataset.list_files(str(flowers_root/'*/*'))

for f in list_ds.take(5):
  print(f.numpy())

b'/root/.keras/datasets/flower_photos/daisy/3625257860_33efeef614_m.jpg'
b'/root/.keras/datasets/flower_photos/sunflowers/2807106374_f422b5f00c.jpg'
b'/root/.keras/datasets/flower_photos/roses/483444865_65962cea07_m.jpg'
b'/root/.keras/datasets/flower_photos/tulips/478765271_6a8ca1cfa1_m.jpg'
b'/root/.keras/datasets/flower_photos/dandelion/8831808134_315aedb37b.jpg'


In [0]:
def process_path(file_path):
  label=tf.strings.split(file_path,'/')[-2]
  return tf.io.read_file(file_path),label

labeled_ds=list_ds.map(process_path)

In [72]:
for image_raw,label_text in labeled_ds.take(1):
  print(repr(image_raw.numpy()[:100]))
  print()
  print(label_text.numpy())

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xe1\n\x13XMP\x00://ns.adobe.com/xap/1.0/\x00<?xpacket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczk'

b'dandelion'


In [73]:
#  Batching dataset elements
inc_dataset=tf.data.Dataset.range(100)
dec_dataset=tf.data.Dataset.range(0,-100,-1)
dataset=tf.data.Dataset.zip((inc_dataset,dec_dataset))
batched_dataset=dataset.batch(4)

for batch in batched_dataset.take(4):
  print([arr.numpy() for arr in batch])

[array([0, 1, 2, 3]), array([ 0, -1, -2, -3])]
[array([4, 5, 6, 7]), array([-4, -5, -6, -7])]
[array([ 8,  9, 10, 11]), array([ -8,  -9, -10, -11])]
[array([12, 13, 14, 15]), array([-12, -13, -14, -15])]


In [74]:
batched_dataset

<BatchDataset shapes: ((None,), (None,)), types: (tf.int64, tf.int64)>

In [75]:
batched_dataset=dataset.batch(7,drop_remainder=True)
batched_dataset

<BatchDataset shapes: ((7,), (7,)), types: (tf.int64, tf.int64)>

In [77]:
# Batching tensors with padding
dataset=tf.data.Dataset.range(100)
dataset=dataset.map(lambda x: tf.fill([tf.cast(x,tf.int32)],x))
dataset=dataset.padded_batch(4,padded_shapes=(None,))

for batch in dataset.take(2):
  print(batch.numpy())
  print()

[[0 0 0]
 [1 0 0]
 [2 2 0]
 [3 3 3]]

[[4 4 4 4 0 0 0]
 [5 5 5 5 5 0 0]
 [6 6 6 6 6 6 0]
 [7 7 7 7 7 7 7]]



In [0]:
# Training Workflow