<a href="https://colab.research.google.com/github/CasCard/Machile-Learning-Project/blob/master/tf.data_Guide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
tf.random.set_seed(1)
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

print(tf.__version__)

TensorFlow 2.x selected.
2.0.0


In [0]:
import pathlib
np.set_printoptions(precision=4)


In [4]:
data=tf.data.Dataset.from_tensor_slices([8,3,0,8,2,1])
data

<TensorSliceDataset shapes: (), types: tf.int32>

In [6]:
for elem in data:
  print(elem.numpy())

8
3
0
8
2
1


In [9]:
it=iter(data)
print(next(it).numpy())

8


In [10]:
print(data.reduce(0,lambda state,value:state+value).numpy())

22


In [11]:
dataset1=tf.data.Dataset.from_tensor_slices(tf.random.uniform([4,10]))
for element in dataset1:
  print(element.numpy())

[0.1651 0.9015 0.631  0.4345 0.2919 0.6425 0.9758 0.4351 0.6601 0.6049]
[0.6366 0.6144 0.8893 0.6278 0.532  0.026  0.4409 0.2527 0.8862 0.8873]
[0.7873 0.0596 0.0711 0.3084 0.2512 0.9085 0.4715 0.2424 0.633  0.586 ]
[0.91   0.5701 0.4964 0.5939 0.5414 0.4429 0.2925 0.7339 0.9197 0.6685]


In [12]:
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [0]:
dataset2=tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([4]),
     tf.random.uniform([4,100],maxval=100,dtype=tf.int32))
)

In [14]:
dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [16]:
dataset3=tf.data.Dataset.zip((dataset1,dataset2))
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(100,), dtype=tf.int32, name=None)))

In [19]:
for elem in dataset3:
  print(elem)

(<tf.Tensor: id=80, shape=(10,), dtype=float32, numpy=
array([0.1651, 0.9015, 0.631 , 0.4345, 0.2919, 0.6425, 0.9758, 0.4351,
       0.6601, 0.6049], dtype=float32)>, (<tf.Tensor: id=81, shape=(), dtype=float32, numpy=0.51010704>, <tf.Tensor: id=82, shape=(100,), dtype=int32, numpy=
array([15, 18, 76, 96, 14, 19, 14, 34, 63, 59, 36, 90, 54,  7, 43, 64, 44,
       95, 35, 24, 43, 76, 38, 31, 95, 11, 71, 24, 38, 19, 14, 17, 66, 81,
       24, 45,  6, 70,  7, 34, 61,  3, 45, 96, 27, 43, 32, 71, 40, 16, 69,
       76, 64, 58, 69, 13, 69, 92, 40, 69,  0, 80, 63, 85,  5, 51,  7, 38,
       23, 61, 66, 88, 26,  5, 17, 82, 59,  0, 80, 45, 73, 95, 75, 90, 35,
       19, 76, 41, 47, 30, 17, 24, 88, 38, 81, 49, 64, 46, 95, 65],
      dtype=int32)>))
(<tf.Tensor: id=83, shape=(10,), dtype=float32, numpy=
array([0.6366, 0.6144, 0.8893, 0.6278, 0.532 , 0.026 , 0.4409, 0.2527,
       0.8862, 0.8873], dtype=float32)>, (<tf.Tensor: id=84, shape=(), dtype=float32, numpy=0.44353175>, <tf.Tensor: id=85, s

In [21]:
dataset4=tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0,0],[1,2]],values=[1,2],dense_shape=[3,4]))
dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [22]:
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor

In [24]:
dataset1=tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4,10],minval=1,maxval=10,dtype=tf.int32))
dataset1

<TensorSliceDataset shapes: (10,), types: tf.int32>

In [27]:
for elem in dataset1:
  print(elem.numpy())

[2 4 4 4 5 7 2 9 9 6]
[5 7 2 4 5 3 1 3 2 3]
[6 4 2 2 6 1 7 3 8 4]
[9 2 6 8 6 4 9 3 2 2]


In [28]:
dataset2=tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([4]),
     tf.random.uniform([4,100],maxval=100,dtype=tf.int32))
)
dataset2

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>

In [30]:
for test in dataset2:
  print(test)

(<tf.Tensor: id=158, shape=(), dtype=float32, numpy=0.734782>, <tf.Tensor: id=159, shape=(100,), dtype=int32, numpy=
array([55, 10, 15, 35, 52, 88, 93,  9, 63, 26,  1, 59,  7, 93, 44, 36, 76,
       50, 98, 51, 18, 38, 50, 31, 56, 37, 21, 79, 45,  4, 42, 33, 79,  0,
       82, 45, 16, 50, 24, 38, 50, 75, 92, 99, 53, 16, 56, 50, 58, 43, 68,
       65, 24, 45, 14, 84, 40, 50, 68, 98, 84, 27, 43, 35, 64, 35, 48, 97,
        0, 46, 12, 16, 19, 81, 77, 64, 52, 87, 43, 44, 70, 72, 51, 65, 25,
       56, 87, 18, 70, 32, 27, 77, 40, 91, 55, 10, 30, 19, 63, 85],
      dtype=int32)>)
(<tf.Tensor: id=160, shape=(), dtype=float32, numpy=0.14221263>, <tf.Tensor: id=161, shape=(100,), dtype=int32, numpy=
array([23, 27, 53, 54, 42, 29, 24, 71, 64, 93, 30, 71,  7, 63, 26, 17, 30,
       58, 60,  4, 57, 87, 88, 13, 26, 73, 35, 67, 70, 42, 51, 94, 19, 33,
       44, 51,  8, 60, 51, 74, 52, 10, 10, 45, 86, 55, 64, 89,  6, 19,  3,
       59, 27, 73, 22, 69, 28,  8, 65, 45, 38, 73, 83, 45, 27, 53, 83, 97,


In [31]:
dataset3=tf.data.Dataset.zip((dataset1,dataset2))
dataset3

<ZipDataset shapes: ((10,), ((), (100,))), types: (tf.int32, (tf.float32, tf.int32))>

In [32]:
for a,(b,c) in dataset3:
  print('shapes: {a.shape},{b.shape},{c.shape}'.format(a=a,b=b,c=c))

shapes: (10,),(),(100,)
shapes: (10,),(),(100,)
shapes: (10,),(),(100,)
shapes: (10,),(),(100,)


In [33]:
train,test=tf.keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [34]:
images,labels=train
images=images/255
dataset=tf.data.Dataset.from_tensor_slices((images,labels))
dataset

<TensorSliceDataset shapes: ((28, 28), ()), types: (tf.float64, tf.uint8)>

In [36]:
def count(stop):
  i=0
  while i<stop:
    yield i
    i+=1

for n in count(5):
  print(n)

0
1
2
3
4


In [0]:
ds_counter=tf.data.Dataset.from_generator(count,args=[25],output_types=tf.int32,output_shapes=(),)


In [40]:
for count_batch in ds_counter.repeat().batch(10).take(5):
  print(count_batch.numpy())

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24  0  1  2  3  4]
[ 5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24]


In [0]:
def gen_series():
  i=0
  while True:
    size=np.random.randint(0,10)
    yield i,np.random.normal(size=(size,))
    i += 1

In [42]:
for i ,series in gen_series():
  print(i,":",str(series))
  if i>5:
    break

0 : [ 0.2403 -1.035   2.9211  0.2408  0.9055  0.6932]
1 : [ 0.6713  0.2674  0.1443  0.1742 -2.651 ]
2 : [-0.8449]
3 : [ 0.7786  0.5757 -0.2319 -1.9504  1.8821  0.9531  0.9939  2.0887]
4 : [-0.4459  0.7888 -0.5667 -1.5875  0.3611]
5 : [1.7289 0.2953]
6 : [-1.1466 -0.9671  0.7132]


In [43]:
ds_series=tf.data.Dataset.from_generator(
    gen_series,
    output_types=(tf.int32,tf.float32),
    output_shapes=((),(None,)))

ds_series

<DatasetV1Adapter shapes: ((), (None,)), types: (tf.int32, tf.float32)>

In [45]:
ds_series_batch=ds_series.shuffle(20).padded_batch(10,padded_shapes=([],[None]))

ids,sequence_batch=next(iter(ds_series_batch))
print(ids.numpy())
print()
print(sequence_batch.numpy())

[13  9 10 22  4  8 25 20 18 14]

[[ 1.5012 -0.5403 -0.8723  0.5297  0.1748  0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.      0.      0.      0.    ]
 [ 0.0944  0.4077  0.3546  0.1813 -1.1926  2.484   0.      0.      0.    ]
 [ 0.6656 -0.5254 -2.1757  0.1863  0.6819 -0.508  -0.0746 -0.0986  0.8986]
 [-0.8089  0.9012 -0.4944  1.827  -0.2467  0.      0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.      0.      0.      0.    ]
 [-0.8374  1.222   1.6837  0.7681 -0.6648 -0.8321 -0.2453  0.      0.    ]
 [ 0.5292  1.1923  0.294   0.      0.      0.      0.      0.      0.    ]
 [ 0.8934 -0.667  -0.1476  0.5793 -0.6421  0.007  -0.3041  0.7923  0.    ]
 [ 0.011  -0.0932 -0.6921  0.658  -0.3096  0.4395  0.6633  0.7819  0.    ]]


In [46]:
flowers=tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True
)

228818944/228813984 [==============================] - 3s 0us/step


In [47]:
img_gen=tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255,rotation_range=20)
images,label=next(img_gen.flow_from_directory(flowers))

Found 3670 images belonging to 5 classes.


In [50]:
print(images.dtype,images.shape)
print(label.dtype,label.shape)

float32 (32, 256, 256, 3)
float32 (32, 5)


In [51]:
ds=tf.data.Dataset.from_generator(
    img_gen.flow_from_directory,args=[flowers],
    output_types=(tf.float32,tf.float32),
    output_shapes=([32,256,256,3],[32,5])
)
ds

<DatasetV1Adapter shapes: ((32, 256, 256, 3), (32, 5)), types: (tf.float32, tf.float32)>

In [52]:
# Consuming TFRecord data
fsns_test_file = tf.keras.utils.get_file("fsns.tfrec", "https://storage.googleapis.com/download.tensorflow.org/data/fsns-20160927/testdata/fsns-00000-of-00001")

7905280/7904079 [==============================] - 0s 0us/step


In [53]:
dataset=tf.data.TFRecordDataset(filenames=[fsns_test_file])
dataset

<TFRecordDatasetV2 shapes: (), types: tf.string>

In [54]:
raw_example=next(iter(dataset))
parsed=tf.train.Example.FromString(raw_example.numpy())
parsed.features.feature['image/text']

bytes_list {
  value: "Rue Perreyon"
}

In [55]:
directory_url = 'https://storage.googleapis.com/download.tensorflow.org/data/illiad/'
file_names = ['cowper.txt', 'derby.txt', 'butler.txt']

file_paths = [
    tf.keras.utils.get_file(file_name, directory_url + file_name)
    for file_name in file_names
]

811008/807992 [==============================] - 0s 0us/step


In [56]:
dataset=tf.data.TextLineDataset(file_paths)
for line in dataset.take(5):
  print(line.numpy())

b"\xef\xbb\xbfAchilles sing, O Goddess! Peleus' son;"
b'His wrath pernicious, who ten thousand woes'
b"Caused to Achaia's host, sent many a soul"
b'Illustrious into Ades premature,'
b'And Heroes gave (so stood the will of Jove)'


In [0]:
# Consuming Text Data